version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:8.11.4

jobs:
  deploy:
    executor:
      name: default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "dc:7f:0f:16:6b:47:d7:79:d5:1e:0b:b8:0c:0d:33:74"
      - checkout
      - run:
          name: install dependencies
          command: |
              npm install gitbook-cli
              git config --global user.name  "ToruNiina"
              git config --global user.email "niina.toru.68u@gmail.com"
              ./node_modules/gitbook-cli/bin/gitbook.js install
              ./node_modules/gitbook-cli/bin/gitbook.js build
              cd _book/
              git init
              git commit --allow-empty -m '[ci skip] update docs'
              git checkout -b gh-pages
              git add .
              git commit -am '[ci skip] update docs'
              git push --force git@github.com:ToruNiina/pnm.git gh-pages


workflows:
  setup_and_deploy:
    jobs:
      - deploy:
          name: update docs
          filters:
            branches:
              only: master

